### ISSUE TITLE
Would using webpack allow me to include/"require" modules asynchronously?

### ISSUE THREAD

**Issue by wqferr** [fengari-lua/fengari-loader#10]
Currently in fengari web, require is a synchronous request. I know very little of web technologies, so apologies if this is a dumb question but can webpack be used to compile modules into async scripts?

**Comment by daurnimator** [comment]
See https://github.com/fengari-lua/fengari-loader?tab=readme-ov-file#how-does-it-work

**Comment by wqferr** [comment]
If I understand correctly, that's a "yes".

Is there a full example I can take a look at somewhere?

**Comment by daurnimator** [comment]
> If I understand correctly, that's a "yes".

It's not totally clear what you're trying to do. e.g. if you just want to preload scripts, you don't need webpack, you can just do it yourself the way you normally do in lua.
However if you are using webpack for your javascript project already, and want to start using fengari/lua modules as well, then this repository is for you.

> Is there a full example I can take a look at somewhere?

I can't think of any public ones off the top of my head

**Comment by wqferr** [comment]
Is there a technique for preloading modules in Lua other than sticking a `package.loaded.modname = M` instead of a return statement in the end of the module?

**Comment by daurnimator** [comment]
> Is there a technique for preloading modules in Lua other than sticking a `package.loaded.modname = M` instead of a return statement in the end of the module?

That's plain loading a module rather than preloading (though it is similar). With preloading, you add a function to `package.preload` that when called, loads the module.
This means you can e.g. delay side effects until the actual module is required for the first time.

**Comment by wqferr** [comment]
OK this makes sense, so thanks for walking me through this far.

I'm still not sure how to actually implement a preloader. Can I set `package.preload` to an async JS function and call it done? No, right?

Or do I just make an HTTP request inside the preload? Won't that be a synchronous request still?

**Comment by daurnimator** [comment]
> Can I set `package.preload` to an async JS function and call it done? No, right?

no, `package.preload` needs to be a synchronous function


> Or do I just make an HTTP request inside the preload? Won't that be a synchronous request still?

You'd make the async request(s) yourself, then when the result comes in, place it into `package.preload`.
Once any/all async requests are done, you would start your script.

**Comment by wqferr** [comment]
So if I have to do the calls myself (I assume with promises), why would I put the results into `package.preload` instead of `package.loaded`?

**Comment by daurnimator** [comment]
> So if I have to do the calls myself (I assume with promises), why would I put the results into `package.preload` instead of `package.loaded`?

Mainly to avoid any possibility of some change in order of a side effect changing the behaviour of a program.

**Comment by wqferr** [comment]
Ok so it makes sense... but I still have no idea how to do this. I'm a Lua dev, I know next to nothing about JavaScript. Could you please include like a 5 line minimum example of what I need to do on the JS side?

**Comment by daurnimator** [comment]
> I'm a Lua dev, I know next to nothing about JavaScript. Could you please include like a 5 line minimum example of what I need to do on the JS side?

Then it sounds like you'll be better off just using the default synchronous require? And then progress to a full solution like webpack when needed.

**Comment by wqferr** [comment]
OK thanks for the help!
