### ISSUE TITLE
fengari-loader build

### ISSUE THREAD

**Issue by mcfly10** [fengari-lua/fengari-loader#8]
Do you have fengari-loader build like for fengari-web? I'm completely frontend developer and don't use Node.js, npm and so on.
I need to use require in lua. So I'd like to download some js file to start using fengari-loader in browser.

**Comment by daurnimator** [comment]
I don't think this request makes sense; fengari-loader is a plugin for webpack: webpack runs on your computer with node js.

**Comment by mcfly10** [comment]
When what is the best practice to use require in LUA on browser side? All links come to fengari-loader. But as I could understand that is server side module.

**Comment by daurnimator** [comment]
> When what is the best practice to use require in LUA on browser side?

fengari-web
